# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Djp4hYHuqjJ2mRqqmUL9m-LY98Mcwom
"""

import numpy as np
import matplotlib.pyplot as plt

# Sinus funksiyasi uchun x qiymatlari
x = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
y = np.sin(x)

# Grafikni chizish
plt.plot(x, y, label="sin(x)", color="blue")
plt.title("Sinus funksiyasi")
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.axhline(0, color="black", linewidth=0.8)
plt.axvline(0, color="black", linewidth=0.8)
plt.grid(color='gray', linestyle='--', linewidth=0.5)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Tasodifiy nuqtalarni yaratish
x = np.random.rand(50) * 10  # X o'qi uchun 50 ta nuqta (0 dan 10 gacha)
y = np.random.rand(50) * 10  # Y o'qi uchun 50 ta nuqta (0 dan 10 gacha)

# Nuqtalar grafigini chizish
plt.scatter(x, y, color='purple', edgecolor='black', s=50, label="Nuqtalar")

# Grafik dizayni
plt.title("Tasodifiy Nuqtalar Grafigi")
plt.xlabel("X qiymatlar")
plt.ylabel("Y qiymatlar")
plt.grid(color='gray', linestyle='--', linewidth=0.5)
plt.legend()
plt.show()